server:
  port: 8080
  
spring:
  application:
    name: spring-mongo-testing
  banner:
    location: classpath:banner.txt  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: io.oferto.testing
  pathsToMatch: /**
  
api:
  common:
    version: 1.0.0
    title: Mongo API
    description: Mongo API
    contact:
      name: Oferto
      url: https://oferto.io
      email: masalinas.gancedo@gmail.com